#!/bin/sh

changed=0

set_opt() {
	local key=$1
	local val=$2

	if ! uci -q get "luci.$key" 2>/dev/null; then
		uci set "luci.$key=$val"
		changed=1
	fi
}

set_opt themes.Gokce /luci-static/gokce

if [ "$PKG_UPGRADE" != 1 ] && [ $changed = 1 ]; then
	set_opt main.mediaurlbase /luci-static/gokce
fi

set_opt themes.GokceDark /luci-static/gokce-dark
set_opt themes.GokceLight /luci-static/gokce-light

if [ $changed = 1 ]; then
	uci commit luci
fi

exit 0
